version: "3.9"

services:
  #  PostgreSQL
  database-postgres:
    image: postgres:14
    container_name: postgressql
    environment:
      - POSTGRES_DB=control
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
    ports:
      - 5432:5432